name: First Soulslike Game
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2025-vs2026
    environment: dev-env
    steps:
      - uses: actions/checkout@v4
      - name: Display Info
        run: |
          echo $(hostname)
          #echo $env:PATH
          dotnet --info
          C:\Progra~2\Microsoft` Visual` Studio\Installer\vswhere.exe -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          choco upgrade curl -y
      - name: Enable MSVC - 让后续shell保有MSVC的环境变量。
        uses: ilammy/msvc-dev-cmd@v1
      - name: Cache Files
        id: cache-files
        uses: actions/cache/restore@v5
        with:
            # 缓存文件夹 - 只读模式
            path: |
              Godot_v4.6.1-stable_mono_linux_x86_64/
            key: godot-v4.6.1-mono4
            enableCrossOsArchive: true
      - name: Test
        run: |
          mkdir ~/AppData/Roaming/Godot/
          mv Godot_v*-stable_mono_linux_x86_64/editor_data/export_templates/ ~/AppData/Roaming/Godot/export_templates/

          curl.exe -L -O https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_mono_win64.zip
          # Expand-Archive 解压命令不支持通配符路径
          7z x "Godot_v*-stable_mono_win64.zip" -y
          #ls Godot_v*-stable_mono_win64/Godot_v*-stable_mono_win64.exe
          
          curl.exe -L -O https://storage.googleapis.com/staging.project-161922.appspot.com/arpg-statecharts.zip
          ls
          7z x "arpg-statecharts.zip" -y
          ls arpg-statecharts/
      - name: Windows Bash
        env:
          NUGET_GITHUB_API_KEY: ${{ secrets.NUGET_GITHUB_API_KEY }}
        shell: bash
        run: |
          rm arpg-statecharts/export_presets.cfg
          cat > arpg-statecharts/export_presets.cfg <<- EOF
          [preset.0]
          name="Windows Desktop"
          platform="Windows Desktop"
          export_path=".godot/mono/x.exe"
          [preset.0.options]
          debug/export_console_wrapper=0
          EOF

          ./Godot_v*-stable_mono_win64/Godot_v*-stable_mono_win64.exe --headless --build-solutions -v --quit --path arpg-statecharts/
          ls arpg-statecharts/
          ./Godot_v*-stable_mono_win64/Godot_v*-stable_mono_win64.exe --headless --export-debug "Windows Desktop" -v --quit --path arpg-statecharts/
      - name: Test Final
        if: ${{ always() }}
        env:
          MY_ENV_VAR: ${{ case(github.ref == 'refs/heads/main', 'production', 'development') }}
        run: |
          #ls arpg-statecharts/.godot/mono/
          7z a -tzip first-soulslike-game.zip C:/Users/runneradmin/AppData/Roaming/Godot/mono/build_logs/
          C:/ProgramData/chocolatey/bin/curl.exe --http2 -F "file=@first-soulslike-game.zip" 'https://abc.passed.app:1443/main/apis/more/default/public/upload-to-storage?storage-provider=tmp&staging&filename=first-soulslike-game.zip'
