name: cpp23
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Display ENV
        run: |
          echo $PATH
      - name: Display clang/clang++
        run: |
          uname -m
          clang++ --version
          sudo apt install libc++-dev libc++abi-dev -y
          # 查找 libc++-dev 的标准库模块文件并编译
          #find /usr/lib/ -name "std.cppm" 2>/dev/null
          ls /usr/lib/llvm-18/share/libc++/v1/
          #clang++ -std=c++23 -stdlib=libc++ -Wno-reserved-identifier -Wno-reserved-module-identifier --precompile -o std.pcm /usr/lib/llvm-18/share/libc++/v1/std.cppm
          #clang++ -std=c++23 -stdlib=libc++ -fmodule-file=std=std.pcm cpp23helloworld.cpp -fsyntax-only
          clang++ -std=c++23 -stdlib=libc++ cpp23helloworld.cpp -fsyntax-only
          ls -la
