name: vs2026
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v4
      - name: Display Info
        run: |
          echo $(hostname)
          #echo $env:PATH
          dotnet --info
      - name: Enable MSVC - 让后续shell保有MSVC的环境变量。
        uses: ilammy/msvc-dev-cmd@v1
      - name: Test
        run: |
          C:\Progra~2\Microsoft` Visual` Studio\Installer\vswhere.exe -latest -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath

          
          $form = @{ file = Get-Item -Path 'C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Auxiliary\Build\vcvarsall.bat' }
          Invoke-WebRequest -Uri 'https://abc.passed.app:1443/main/apis/more/default/public/upload-to-storage?storage-provider=tmp&staging&filename=x.exe' -Method Post -Form $form -SkipCertificateCheck
          
          #dotnet new console -o hi --aot
          #dotnet publish hi/hi.csproj -r win-x64 -p:DisableUnsupportedError=true -p:PublishAotUsingRuntimePack=true
          #ls hi/bin/x64/Release/net*.0/win-x64/publish/* -ErrorAction SilentlyContinue
