name: vs2026
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v4
      - name: Display Info
        run: |
          echo $(hostname)
      - name: Enable MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Test
        run: |
          dotnet --info
